
# using 'docker-compose up' restarts the docker service
# using 'docker-compose down' stopping everything that was happeing

# docker-php-ext-install pdo pdo_mysql mysqli

version: '3' # Docker Version
services:
  www:
    build: 
      context: .
      dockerfile: Dockerfile.php
    image: php:apache # pulls apache image for php
    volumes:
      - "./:/var/www/html" # sync project dir with container web dir
    ports:
      - 8080:80
      - 8443:443 # for future ssl traffic
  db:
    image: mysql:latest # pulls the latest image of mysql from docker
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - "./db:/docker-entrypoint-initdb.d" #sync persistent sql files with container
  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8001:80
    environment:
      - PMA_HOST=db
  mailserver:
    image: mailserver/docker-mailserver:latest
    hostname: mail
    domainname: starpoint.com
    container_name: mailserver
    ports:
      - 25:25
      - 143:143
      - 587:587
      - 993:993
    volumes:
      - ~/docker-mailstate:/var/mail-state
      - /var/mail:/var/mail
      - ./config/:/tmp/docker-mailserver/

    environment:
      - ENABLE_SPAMASSASSIN=1
      - ENABLE_CLAMAV=1
      - ENABLE_FAIL2BAN=1
      - ENABLE_POSTGREY=1
      - ONE_DIR=1
      - DMS_DEBUG=0
    cap_add:
      - NET_ADMIN
      - SYS_PTRACE

networks:
  default:
    name: mail_network
    external: true
