# using 'docker-compose up' restarts the docker service
# using 'docker-compose down' stopping everything that was happeing
# docker-php-ext-install pdo pdo_mysql mysqli

# Docker Version
version: '3' 
services:
  www:
    build: 
        context: .
        dockerfile: Dockerfile.php
    image: php:apache
    volumes:
      - "./:/var/www/html"
    ports:
      - 8080:80
      - 8443:443
  db:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - "./db:/docker-entrypoint-initdb.d"
  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8001:80
    environment:
      - PMA_HOST=db
